[[constraint]]
  branch = "master"
  name = "github.com/Unknwon/goconfig"

[[constraint]]
  branch = "master"
  name = "github.com/cbroglie/mustache"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/static"

[[constraint]]
  branch = "master"
  name = "github.com/gregjones/httpcache"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
